// MIT License
// Copyright (c) 2026 dbjwhs

// Generated by songc - DO NOT EDIT
// Source: stockticker.song

#pragma once

#include <song/song.hpp>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>

namespace song::stockticker {

using namespace song;

// Service and method IDs
constexpr u16 kService_StockTicker = 1;
constexpr u16 kMethod_StockTicker_get_quote = 1;
constexpr u16 kMethod_StockTicker_get_quotes = 2;
constexpr u16 kMethod_StockTicker_get_history = 3;
constexpr u16 kMethod_StockTicker_get_market_status = 4;
constexpr u16 kMethod_StockTicker_symbol_exists = 5;
constexpr u16 kMethod_StockTicker_list_symbols = 6;

struct Quote;
struct PricePoint;
struct MarketStatus;

/// A stock quote with price and metadata
struct Quote {
    /// Stock symbol (e.g., "AAPL")
    std::string symbol;
    /// Current price in cents (to avoid float precision issues)
    i64 price_cents;
    /// Price change from previous close in cents
    i64 change_cents;
    /// Volume traded today
    i64 volume;
    /// Timestamp of quote (unix milliseconds)
    i64 timestamp;
};

/// Historical price point
struct PricePoint {
    /// Timestamp (unix milliseconds)
    i64 timestamp;
    /// Price in cents
    i64 price_cents;
    /// Volume at this point
    i64 volume;
};

/// Market status information
struct MarketStatus {
    /// Whether market is currently open
    bool is_open;
    /// Next market open time (unix milliseconds)
    i64 next_open;
    /// Next market close time (unix milliseconds)
    i64 next_close;
    /// Status message
    std::string message;
};

// Forward declare array helpers
inline void encode_array_Quote(Buffer& buf, const std::vector<Quote>& arr);
inline std::vector<Quote> decode_array_Quote(Buffer& buf);
inline void encode_array_PricePoint(Buffer& buf, const std::vector<PricePoint>& arr);
inline std::vector<PricePoint> decode_array_PricePoint(Buffer& buf);
inline void encode_array_MarketStatus(Buffer& buf, const std::vector<MarketStatus>& arr);
inline std::vector<MarketStatus> decode_array_MarketStatus(Buffer& buf);

// Serialization
inline void encode_Quote(Buffer& buf, const Quote& val) {
    encode_string(buf, val.symbol);
    encode_i64(buf, val.price_cents);
    encode_i64(buf, val.change_cents);
    encode_i64(buf, val.volume);
    encode_i64(buf, val.timestamp);
}

inline Quote decode_Quote(Buffer& buf) {
    Quote val;
    val.symbol = decode_string(buf);
    val.price_cents = decode_i64(buf);
    val.change_cents = decode_i64(buf);
    val.volume = decode_i64(buf);
    val.timestamp = decode_i64(buf);
    return val;
}

inline void encode_PricePoint(Buffer& buf, const PricePoint& val) {
    encode_i64(buf, val.timestamp);
    encode_i64(buf, val.price_cents);
    encode_i64(buf, val.volume);
}

inline PricePoint decode_PricePoint(Buffer& buf) {
    PricePoint val;
    val.timestamp = decode_i64(buf);
    val.price_cents = decode_i64(buf);
    val.volume = decode_i64(buf);
    return val;
}

inline void encode_MarketStatus(Buffer& buf, const MarketStatus& val) {
    encode_bool(buf, val.is_open);
    encode_i64(buf, val.next_open);
    encode_i64(buf, val.next_close);
    encode_string(buf, val.message);
}

inline MarketStatus decode_MarketStatus(Buffer& buf) {
    MarketStatus val;
    val.is_open = decode_bool(buf);
    val.next_open = decode_i64(buf);
    val.next_close = decode_i64(buf);
    val.message = decode_string(buf);
    return val;
}

inline void encode_array_Quote(Buffer& buf, const std::vector<Quote>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_Quote(buf, val);
    }
}

inline std::vector<Quote> decode_array_Quote(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<Quote> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_Quote(buf));
    }
    return arr;
}

inline void encode_array_PricePoint(Buffer& buf, const std::vector<PricePoint>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_PricePoint(buf, val);
    }
}

inline std::vector<PricePoint> decode_array_PricePoint(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<PricePoint> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_PricePoint(buf));
    }
    return arr;
}

inline void encode_array_MarketStatus(Buffer& buf, const std::vector<MarketStatus>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_MarketStatus(buf, val);
    }
}

inline std::vector<MarketStatus> decode_array_MarketStatus(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<MarketStatus> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_MarketStatus(buf));
    }
    return arr;
}

/// Stock ticker service
class StockTickerProxy {
    ServiceConnection& m_conn;
public:
    explicit StockTickerProxy(ServiceConnection& conn) : m_conn(conn) {}

    /// Get current quote for a symbol
    Quote get_quote(const std::string& symbol) {
        Buffer req;
        encode_string(req, symbol);
        Buffer resp = m_conn.call(kService_StockTicker, kMethod_StockTicker_get_quote, req);
        return decode_Quote(resp);
    }

    /// Get quotes for multiple symbols at once
    std::vector<Quote> get_quotes(const std::vector<std::string>& symbols) {
        Buffer req;
        encode_array<std::string>(req, symbols);
        Buffer resp = m_conn.call(kService_StockTicker, kMethod_StockTicker_get_quotes, req);
        return decode_array_Quote(resp);
    }

    /// Get price history for a symbol (last N points)
    std::vector<PricePoint> get_history(const std::string& symbol, i32 points) {
        Buffer req;
        encode_string(req, symbol);
        encode_i32(req, points);
        Buffer resp = m_conn.call(kService_StockTicker, kMethod_StockTicker_get_history, req);
        return decode_array_PricePoint(resp);
    }

    /// Get current market status
    MarketStatus get_market_status() {
        Buffer req;
        Buffer resp = m_conn.call(kService_StockTicker, kMethod_StockTicker_get_market_status, req);
        return decode_MarketStatus(resp);
    }

    /// Check if a symbol exists
    bool symbol_exists(const std::string& symbol) {
        Buffer req;
        encode_string(req, symbol);
        Buffer resp = m_conn.call(kService_StockTicker, kMethod_StockTicker_symbol_exists, req);
        return decode_bool(resp);
    }

    /// Get list of all available symbols
    std::vector<std::string> list_symbols() {
        Buffer req;
        Buffer resp = m_conn.call(kService_StockTicker, kMethod_StockTicker_list_symbols, req);
        return decode_array<std::string>(resp);
    }

};

/// Stock ticker service (interface)
class IStockTicker {
public:
    virtual ~IStockTicker() = default;

    /// Get current quote for a symbol
    virtual Quote get_quote(const std::string& symbol) = 0;
    /// Get quotes for multiple symbols at once
    virtual std::vector<Quote> get_quotes(const std::vector<std::string>& symbols) = 0;
    /// Get price history for a symbol (last N points)
    virtual std::vector<PricePoint> get_history(const std::string& symbol, i32 points) = 0;
    /// Get current market status
    virtual MarketStatus get_market_status() = 0;
    /// Check if a symbol exists
    virtual bool symbol_exists(const std::string& symbol) = 0;
    /// Get list of all available symbols
    virtual std::vector<std::string> list_symbols() = 0;
};

inline void dispatch_StockTicker(IStockTicker& impl, u16 method_id, Buffer& request, Buffer& response) {
    switch (method_id) {
        case kMethod_StockTicker_get_quote: {
            std::string symbol = decode_string(request);
            auto result = impl.get_quote(symbol);
            encode_Quote(response, result);
            break;
        }
        case kMethod_StockTicker_get_quotes: {
            std::vector<std::string> symbols = decode_array<std::string>(request);
            auto result = impl.get_quotes(symbols);
            encode_array_Quote(response, result);
            break;
        }
        case kMethod_StockTicker_get_history: {
            std::string symbol = decode_string(request);
            i32 points = decode_i32(request);
            auto result = impl.get_history(symbol, points);
            encode_array_PricePoint(response, result);
            break;
        }
        case kMethod_StockTicker_get_market_status: {
            auto result = impl.get_market_status();
            encode_MarketStatus(response, result);
            break;
        }
        case kMethod_StockTicker_symbol_exists: {
            std::string symbol = decode_string(request);
            auto result = impl.symbol_exists(symbol);
            encode_bool(response, result);
            break;
        }
        case kMethod_StockTicker_list_symbols: {
            auto result = impl.list_symbols();
            encode_array<std::string>(response, result);
            break;
        }
        default:
            throw std::runtime_error("Unknown method ID: " + std::to_string(method_id));
    }
}

} // namespace song::stockticker
