// MIT License
// Copyright (c) 2026 dbjwhs

#include <gtest/gtest.h>
#include "parser.hpp"
#include "resolver.hpp"
#include "python_codegen.hpp"
#include <song/buffer.hpp>
#include <cstdlib>
#include <filesystem>
#include <fstream>

using namespace song;
using namespace song::compiler;

// Helper to parse, resolve, and generate Python code
static std::string parse_and_generate_python(const std::string& source) {
    Parser parser(source);
    auto ast = parser.parse();

    Resolver resolver(ast);
    EXPECT_TRUE(resolver.resolve());

    PythonCodeGenerator gen;
    return gen.generate_module(ast.namespaces.front());
}

// =============================================================================
// Module Structure
// =============================================================================

TEST(PythonCodegenTest, ModuleHeader) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Point {
            i32 x;
            i32 y;
        }
    )");

    // Should contain generated file header
    EXPECT_NE(code.find("# Generated by songc - DO NOT EDIT"), std::string::npos);
    // Should import dataclass
    EXPECT_NE(code.find("from dataclasses import dataclass"), std::string::npos);
    // Should import IntEnum
    EXPECT_NE(code.find("from enum import IntEnum"), std::string::npos);
    // Should import song buffer and connection
    EXPECT_NE(code.find("from song.buffer import Buffer"), std::string::npos);
    EXPECT_NE(code.find("from song.connection import ServiceConnection"), std::string::npos);
}

// =============================================================================
// Struct Generation
// =============================================================================

TEST(PythonCodegenTest, SimpleStruct) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Point {
            i32 x;
            i32 y;
        }
    )");

    // Should contain dataclass definition
    EXPECT_NE(code.find("@dataclass"), std::string::npos);
    EXPECT_NE(code.find("class Point:"), std::string::npos);
    EXPECT_NE(code.find("x: int"), std::string::npos);
    EXPECT_NE(code.find("y: int"), std::string::npos);

    // Should contain encode/decode functions
    EXPECT_NE(code.find("def encode_Point(buf: Buffer, val: Point) -> None:"), std::string::npos);
    EXPECT_NE(code.find("def decode_Point(buf: Buffer) -> Point:"), std::string::npos);
}

TEST(PythonCodegenTest, StructWithAllPrimitives) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct AllTypes {
            bool flag;
            i8 byte_val;
            i16 short_val;
            i32 int_val;
            i64 long_val;
            u8 ubyte_val;
            u16 ushort_val;
            u32 uint_val;
            u64 ulong_val;
            f32 float_val;
            f64 double_val;
            string name;
            bytes data;
        }
    )");

    // Python type mappings
    EXPECT_NE(code.find("flag: bool"), std::string::npos);
    EXPECT_NE(code.find("byte_val: int"), std::string::npos);
    EXPECT_NE(code.find("int_val: int"), std::string::npos);
    EXPECT_NE(code.find("float_val: float"), std::string::npos);
    EXPECT_NE(code.find("double_val: float"), std::string::npos);
    EXPECT_NE(code.find("name: str"), std::string::npos);
    EXPECT_NE(code.find("data: bytes"), std::string::npos);

    // Encode calls should use correct buffer methods
    EXPECT_NE(code.find("buf.encode_bool(val.flag)"), std::string::npos);
    EXPECT_NE(code.find("buf.encode_i32(val.int_val)"), std::string::npos);
    EXPECT_NE(code.find("buf.encode_f64(val.double_val)"), std::string::npos);
    EXPECT_NE(code.find("buf.encode_string(val.name)"), std::string::npos);
    EXPECT_NE(code.find("buf.encode_bytes(val.data)"), std::string::npos);
}

TEST(PythonCodegenTest, StructWithUserType) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Point {
            i32 x;
            i32 y;
        }
        struct Rect {
            Point origin;
            Point size;
        }
    )");

    EXPECT_NE(code.find("class Rect:"), std::string::npos);
    EXPECT_NE(code.find("origin: Point"), std::string::npos);
    EXPECT_NE(code.find("size: Point"), std::string::npos);

    // User type encode/decode should call struct-level functions with buf
    EXPECT_NE(code.find("encode_Point(buf, val.origin)"), std::string::npos);
    EXPECT_NE(code.find("decode_Point(buf)"), std::string::npos);
}

TEST(PythonCodegenTest, StructWithOptionalField) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Config {
            string name;
            i32? timeout;
        }
    )");

    EXPECT_NE(code.find("timeout: Optional[int] = None"), std::string::npos);
}

TEST(PythonCodegenTest, StructWithArray) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Numbers {
            i32[] values;
            string[] names;
        }
    )");

    EXPECT_NE(code.find("values: list[int]"), std::string::npos);
    EXPECT_NE(code.find("names: list[str]"), std::string::npos);
    EXPECT_NE(code.find("encode_array_i32(val.values)"), std::string::npos);
    EXPECT_NE(code.find("encode_array_string(val.names)"), std::string::npos);
}

TEST(PythonCodegenTest, StructDocComment) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        /// A 2D point
        struct Point {
            i32 x;
            i32 y;
        }
    )");

    EXPECT_NE(code.find("\"\"\"A 2D point\"\"\""), std::string::npos);
}

TEST(PythonCodegenTest, EmptyStruct) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Empty {
        }
    )");

    EXPECT_NE(code.find("class Empty:"), std::string::npos);
    EXPECT_NE(code.find("pass"), std::string::npos);
}

// =============================================================================
// Enum Generation
// =============================================================================

TEST(PythonCodegenTest, SimpleEnum) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        enum Color {
            Red,
            Green,
            Blue
        }
    )");

    EXPECT_NE(code.find("class Color(IntEnum):"), std::string::npos);
    EXPECT_NE(code.find("Red = 0"), std::string::npos);
    EXPECT_NE(code.find("Green = 1"), std::string::npos);
    EXPECT_NE(code.find("Blue = 2"), std::string::npos);
}

TEST(PythonCodegenTest, EnumWithExplicitValues) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        enum Status {
            Ok = 200,
            NotFound = 404,
            Error = 500
        }
    )");

    EXPECT_NE(code.find("Ok = 200"), std::string::npos);
    EXPECT_NE(code.find("NotFound = 404"), std::string::npos);
    EXPECT_NE(code.find("Error = 500"), std::string::npos);
}

// =============================================================================
// Service Generation
// =============================================================================

TEST(PythonCodegenTest, ServiceIDs) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        service Calculator {
            add(i32 a, i32 b) -> i32;
            subtract(i32 a, i32 b) -> i32;
        }
    )");

    EXPECT_NE(code.find("SERVICE_Calculator = 1"), std::string::npos);
    EXPECT_NE(code.find("METHOD_Calculator_add = 1"), std::string::npos);
    EXPECT_NE(code.find("METHOD_Calculator_subtract = 2"), std::string::npos);
}

TEST(PythonCodegenTest, ServiceProxy) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        service Calculator {
            add(i32 a, i32 b) -> i32;
        }
    )");

    EXPECT_NE(code.find("class CalculatorProxy:"), std::string::npos);
    EXPECT_NE(code.find("def __init__(self, conn: ServiceConnection):"), std::string::npos);
    EXPECT_NE(code.find("self._conn = conn"), std::string::npos);
    EXPECT_NE(code.find("def add(self, a: int, b: int) -> int:"), std::string::npos);
}

TEST(PythonCodegenTest, ServiceProxyMethodBody) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        service Calculator {
            add(i32 a, i32 b) -> i32;
        }
    )");

    // Method body should encode parameters
    EXPECT_NE(code.find("req = Buffer()"), std::string::npos);
    EXPECT_NE(code.find("req.encode_i32(a)"), std::string::npos);
    EXPECT_NE(code.find("req.encode_i32(b)"), std::string::npos);

    // Should call service
    EXPECT_NE(code.find("self._conn.call(SERVICE_Calculator, METHOD_Calculator_add, req)"), std::string::npos);

    // Should decode response
    EXPECT_NE(code.find("return resp.decode_i32()"), std::string::npos);
}

TEST(PythonCodegenTest, ServiceProxyVoidReturn) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        service Logger {
            log(string message) -> void;
        }
    )");

    EXPECT_NE(code.find("def log(self, message: str) -> None:"), std::string::npos);
    EXPECT_NE(code.find("req.encode_string(message)"), std::string::npos);
    // Void return should not decode response
    EXPECT_EQ(code.find("return resp.decode"), std::string::npos);
}

TEST(PythonCodegenTest, ServiceProxyWithStruct) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Point {
            i32 x;
            i32 y;
        }
        service Geometry {
            distance(Point a, Point b) -> f64;
        }
    )");

    EXPECT_NE(code.find("def distance(self, a: Point, b: Point) -> float:"), std::string::npos);
    EXPECT_NE(code.find("encode_Point(req, a)"), std::string::npos);
    EXPECT_NE(code.find("encode_Point(req, b)"), std::string::npos);
    EXPECT_NE(code.find("return resp.decode_f64()"), std::string::npos);
}

TEST(PythonCodegenTest, MultipleServices) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        service Auth {
            login(string user, string pass) -> bool;
        }
        service Data {
            get(i32 id) -> string;
        }
    )");

    EXPECT_NE(code.find("SERVICE_Auth = 1"), std::string::npos);
    EXPECT_NE(code.find("SERVICE_Data = 2"), std::string::npos);
    EXPECT_NE(code.find("class AuthProxy:"), std::string::npos);
    EXPECT_NE(code.find("class DataProxy:"), std::string::npos);
}

// =============================================================================
// Complex / Integration
// =============================================================================

TEST(PythonCodegenTest, CompleteModule) {
    std::string code = parse_and_generate_python(R"(
        namespace calculator;

        struct DivResult {
            i32 quotient;
            i32 remainder;
        }

        enum Operation {
            Add,
            Subtract,
            Multiply,
            Divide
        }

        service Calculator {
            add(i32 a, i32 b) -> i32;
            divide(i32 a, i32 b) -> DivResult;
        }
    )");

    // Module should have correct namespace reference
    EXPECT_NE(code.find("# Source: calculator.song"), std::string::npos);

    // All components should be present
    EXPECT_NE(code.find("class DivResult:"), std::string::npos);
    EXPECT_NE(code.find("class Operation(IntEnum):"), std::string::npos);
    EXPECT_NE(code.find("class CalculatorProxy:"), std::string::npos);

    // Struct should come before service proxy (order matters for Python)
    auto struct_pos = code.find("class DivResult:");
    auto proxy_pos = code.find("class CalculatorProxy:");
    EXPECT_LT(struct_pos, proxy_pos);
}

TEST(PythonCodegenTest, ServiceProxyDocComment) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        /// A calculator service
        service Calculator {
            add(i32 a, i32 b) -> i32;
        }
    )");

    EXPECT_NE(code.find("\"\"\"A calculator service\"\"\""), std::string::npos);
}

TEST(PythonCodegenTest, ServiceProxyDefaultDocComment) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        service Calculator {
            add(i32 a, i32 b) -> i32;
        }
    )");

    EXPECT_NE(code.find("\"\"\"Client proxy for Calculator service.\"\"\""), std::string::npos);
}

TEST(PythonCodegenTest, ArrayTypeHints) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Matrix {
            f64[][] data;
        }
    )");

    EXPECT_NE(code.find("data: list[list[float]]"), std::string::npos);
    // Multi-dimensional arrays now generate proper encode/decode loops
    EXPECT_EQ(code.find("NotImplementedError"), std::string::npos);
    EXPECT_NE(code.find("encode_u32"), std::string::npos);
}

TEST(PythonCodegenTest, UserTypeArray) {
    std::string code = parse_and_generate_python(R"(
        namespace test;
        struct Point {
            i32 x;
            i32 y;
        }
        struct Polygon {
            Point[] vertices;
        }
    )");

    EXPECT_NE(code.find("vertices: list[Point]"), std::string::npos);
    // User-type arrays should generate proper encode/decode loops
    EXPECT_NE(code.find("encode_Point"), std::string::npos);
    EXPECT_NE(code.find("decode_Point"), std::string::npos);
    // Should NOT have NotImplementedError for user-type arrays
    auto polygon_pos = code.find("def encode_Polygon");
    auto not_impl_pos = code.find("NotImplementedError", polygon_pos);
    EXPECT_EQ(not_impl_pos, std::string::npos);

    // Verify struct encode has correct 4-space indentation for the for loop
    // (not 8-space which would be a Python IndentationError)
    EXPECT_NE(code.find("    for _item in"), std::string::npos)
        << "Struct encode should use 4-space indent for loop body";
    // The loop body should be indented one more level (8 spaces)
    EXPECT_NE(code.find("        encode_Point"), std::string::npos)
        << "Loop body should use 8-space indent";
}

// =============================================================================
// Python-C++ Wire Round-Trip
// =============================================================================

TEST(PythonCodegenTest, WireRoundTrip) {
    // Encode known values in Python using struct module (matching Song wire
    // format: little-endian, u32-length-prefixed strings), write to a binary
    // file, then decode in C++ with Buffer and verify values match.

    // Check python3 is available
    if (std::system("python3 --version >/dev/null 2>&1") != 0) {
        GTEST_SKIP() << "python3 not available";
    }

    auto tmp_dir = std::filesystem::temp_directory_path();
    auto py_path = tmp_dir / "song_wire_roundtrip.py";
    auto bin_path = tmp_dir / "song_wire_roundtrip.bin";

    // Write a Python script that encodes values using Song's wire format:
    //   i32: 42
    //   i64: 123456789
    //   f64: 3.14159
    //   string: "Hello, Song!"
    //   i32: -1
    {
        std::ofstream pf(py_path);
        ASSERT_TRUE(pf.is_open());
        pf << R"PY(
import struct, sys

buf = bytearray()

# i32: little-endian signed 32-bit
buf += struct.pack('<i', 42)

# i64: little-endian signed 64-bit
buf += struct.pack('<q', 123456789)

# f64: little-endian double
buf += struct.pack('<d', 3.14159)

# string: u32 length prefix + raw bytes
s = b'Hello, Song!'
buf += struct.pack('<I', len(s))
buf += s

# i32: -1 (two's complement boundary)
buf += struct.pack('<i', -1)

with open(sys.argv[1], 'wb') as f:
    f.write(buf)
)PY";
    }

    // Run Python to generate binary
    std::string cmd = "python3 " + py_path.string() + " " + bin_path.string() + " 2>&1";
    int ret = std::system(cmd.c_str());
    ASSERT_EQ(ret, 0) << "Python script failed";

    // Read binary into Buffer
    std::ifstream bf(bin_path, std::ios::binary);
    ASSERT_TRUE(bf.is_open());
    std::vector<char> data((std::istreambuf_iterator<char>(bf)),
                            std::istreambuf_iterator<char>());
    bf.close();

    Buffer buf;
    buf.write(data.data(), data.size());
    buf.reset_read();

    // Decode and verify each value matches what Python encoded
    EXPECT_EQ(decode_i32(buf), 42);
    EXPECT_EQ(decode_i64(buf), 123456789LL);
    EXPECT_NEAR(decode_f64(buf), 3.14159, 1e-10);
    EXPECT_EQ(decode_string(buf), "Hello, Song!");
    EXPECT_EQ(decode_i32(buf), -1);

    // Clean up
    std::filesystem::remove(py_path);
    std::filesystem::remove(bin_path);
}

TEST(PythonCodegenTest, WireRoundTripReverse) {
    // Encode values in C++, write to binary file, decode in Python, verify match.

    if (std::system("python3 --version >/dev/null 2>&1") != 0) {
        GTEST_SKIP() << "python3 not available";
    }

    auto tmp_dir = std::filesystem::temp_directory_path();
    auto bin_path = tmp_dir / "song_wire_reverse.bin";
    auto py_path = tmp_dir / "song_wire_reverse.py";

    // Encode in C++
    Buffer buf;
    encode_i32(buf, 99);
    encode_i64(buf, -987654321LL);
    encode_f64(buf, 2.71828);
    encode_string(buf, "Song RPC");
    encode_i32(buf, 0);

    // Write buffer to file
    {
        std::ofstream of(bin_path, std::ios::binary);
        ASSERT_TRUE(of.is_open());
        of.write(reinterpret_cast<const char*>(buf.data()), static_cast<std::streamsize>(buf.size()));
    }

    // Write Python script that decodes and verifies
    {
        std::ofstream pf(py_path);
        ASSERT_TRUE(pf.is_open());
        pf << R"PY(
import struct, sys

with open(sys.argv[1], 'rb') as f:
    data = f.read()

offset = 0

def read(fmt):
    global offset
    size = struct.calcsize(fmt)
    val = struct.unpack_from(fmt, data, offset)
    offset += size
    return val[0]

# i32: 99
assert read('<i') == 99, "i32 mismatch"

# i64: -987654321
assert read('<q') == -987654321, "i64 mismatch"

# f64: 2.71828
val = read('<d')
assert abs(val - 2.71828) < 1e-10, f"f64 mismatch: {val}"

# string: "Song RPC"
slen = read('<I')
s = data[offset:offset+slen].decode('utf-8')
offset += slen
assert s == "Song RPC", f"string mismatch: {s}"

# i32: 0
assert read('<i') == 0, "i32 zero mismatch"

print("OK")
)PY";
    }

    std::string cmd = "python3 " + py_path.string() + " " + bin_path.string() + " 2>&1";
    int ret = std::system(cmd.c_str());

    // Clean up
    std::filesystem::remove(py_path);
    std::filesystem::remove(bin_path);

    EXPECT_EQ(ret, 0) << "Python decode verification failed";
}
