// MIT License
// Copyright (c) 2026 dbjwhs

// Generated by songc - DO NOT EDIT
// Source: backup.song

#pragma once

#include <song/song.hpp>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>

namespace song::backup {

using namespace song;

// Service and method IDs
constexpr u16 kService_BackupAgent = 1;
constexpr u16 kMethod_BackupAgent_list_files = 1;
constexpr u16 kMethod_BackupAgent_get_file_info = 2;
constexpr u16 kMethod_BackupAgent_file_exists = 3;
constexpr u16 kMethod_BackupAgent_changes_since = 4;
constexpr u16 kMethod_BackupAgent_receive_chunk = 5;
constexpr u16 kMethod_BackupAgent_delete_file = 6;
constexpr u16 kMethod_BackupAgent_get_progress = 7;
constexpr u16 kMethod_BackupAgent_get_storage_used = 8;
constexpr u16 kMethod_BackupAgent_compute_checksum = 9;

struct FileEntry;
struct FileChunk;
struct ChunkResult;
struct Progress;

/// Status of a backup operation
enum class BackupStatus : i32 {
    idle = 0,
    scanning = 1,
    transferring = 2,
    complete = 3,
    failed = 4
};

/// Information about a file on the backup agent
struct FileEntry {
    /// Relative path within the backup root
    std::string path;
    /// File size in bytes
    i64 size;
    /// Last modification time (unix milliseconds)
    i64 modified_at;
    /// SHA-256 checksum (hex string, empty if not computed)
    std::string checksum;
};

/// A chunk of file data for transfer
struct FileChunk {
    /// Relative path of the file
    std::string path;
    /// Byte offset within the file
    i64 offset;
    /// Chunk payload
    std::vector<std::byte> data;
    /// Whether this is the last chunk
    bool is_final;
};

/// Result of receiving a chunk
struct ChunkResult {
    /// Whether the write succeeded
    bool success;
    /// Bytes written in this chunk
    i64 bytes_written;
    /// Total bytes received for this file so far
    i64 total_received;
};

/// Progress of an ongoing operation
struct Progress {
    /// Current file being processed
    std::string current_file;
    /// Files completed so far
    i32 files_done;
    /// Total files to process
    i32 files_total;
    /// Bytes transferred so far
    i64 bytes_done;
    /// Total bytes to transfer
    i64 bytes_total;
    /// BackupStatus value
    i32 status;
};

// Forward declare array helpers
inline void encode_array_FileEntry(Buffer& buf, const std::vector<FileEntry>& arr);
inline std::vector<FileEntry> decode_array_FileEntry(Buffer& buf);
inline void encode_array_FileChunk(Buffer& buf, const std::vector<FileChunk>& arr);
inline std::vector<FileChunk> decode_array_FileChunk(Buffer& buf);
inline void encode_array_ChunkResult(Buffer& buf, const std::vector<ChunkResult>& arr);
inline std::vector<ChunkResult> decode_array_ChunkResult(Buffer& buf);
inline void encode_array_Progress(Buffer& buf, const std::vector<Progress>& arr);
inline std::vector<Progress> decode_array_Progress(Buffer& buf);

// Serialization
inline void encode_FileEntry(Buffer& buf, const FileEntry& val) {
    encode_string(buf, val.path);
    encode_i64(buf, val.size);
    encode_i64(buf, val.modified_at);
    encode_string(buf, val.checksum);
}

inline FileEntry decode_FileEntry(Buffer& buf) {
    FileEntry val;
    val.path = decode_string(buf);
    val.size = decode_i64(buf);
    val.modified_at = decode_i64(buf);
    val.checksum = decode_string(buf);
    return val;
}

inline void encode_FileChunk(Buffer& buf, const FileChunk& val) {
    encode_string(buf, val.path);
    encode_i64(buf, val.offset);
    encode_bytes(buf, val.data);
    encode_bool(buf, val.is_final);
}

inline FileChunk decode_FileChunk(Buffer& buf) {
    FileChunk val;
    val.path = decode_string(buf);
    val.offset = decode_i64(buf);
    val.data = decode_bytes(buf);
    val.is_final = decode_bool(buf);
    return val;
}

inline void encode_ChunkResult(Buffer& buf, const ChunkResult& val) {
    encode_bool(buf, val.success);
    encode_i64(buf, val.bytes_written);
    encode_i64(buf, val.total_received);
}

inline ChunkResult decode_ChunkResult(Buffer& buf) {
    ChunkResult val;
    val.success = decode_bool(buf);
    val.bytes_written = decode_i64(buf);
    val.total_received = decode_i64(buf);
    return val;
}

inline void encode_Progress(Buffer& buf, const Progress& val) {
    encode_string(buf, val.current_file);
    encode_i32(buf, val.files_done);
    encode_i32(buf, val.files_total);
    encode_i64(buf, val.bytes_done);
    encode_i64(buf, val.bytes_total);
    encode_i32(buf, val.status);
}

inline Progress decode_Progress(Buffer& buf) {
    Progress val;
    val.current_file = decode_string(buf);
    val.files_done = decode_i32(buf);
    val.files_total = decode_i32(buf);
    val.bytes_done = decode_i64(buf);
    val.bytes_total = decode_i64(buf);
    val.status = decode_i32(buf);
    return val;
}

inline void encode_array_FileEntry(Buffer& buf, const std::vector<FileEntry>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_FileEntry(buf, val);
    }
}

inline std::vector<FileEntry> decode_array_FileEntry(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<FileEntry> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_FileEntry(buf));
    }
    return arr;
}

inline void encode_array_FileChunk(Buffer& buf, const std::vector<FileChunk>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_FileChunk(buf, val);
    }
}

inline std::vector<FileChunk> decode_array_FileChunk(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<FileChunk> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_FileChunk(buf));
    }
    return arr;
}

inline void encode_array_ChunkResult(Buffer& buf, const std::vector<ChunkResult>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_ChunkResult(buf, val);
    }
}

inline std::vector<ChunkResult> decode_array_ChunkResult(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<ChunkResult> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_ChunkResult(buf));
    }
    return arr;
}

inline void encode_array_Progress(Buffer& buf, const std::vector<Progress>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_Progress(buf, val);
    }
}

inline std::vector<Progress> decode_array_Progress(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<Progress> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_Progress(buf));
    }
    return arr;
}

/// Backup agent service
class BackupAgentProxy {
    ServiceConnection& m_conn;
public:
    explicit BackupAgentProxy(ServiceConnection& conn) : m_conn(conn) {}

    /// List all files under the backup root
    std::vector<FileEntry> list_files() {
        Buffer req;
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_list_files, req);
        return decode_array_FileEntry(resp);
    }

    /// Get info about a specific file
    FileEntry get_file_info(const std::string& path) {
        Buffer req;
        encode_string(req, path);
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_get_file_info, req);
        return decode_FileEntry(resp);
    }

    /// Check if a file exists
    bool file_exists(const std::string& path) {
        Buffer req;
        encode_string(req, path);
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_file_exists, req);
        return decode_bool(resp);
    }

    /// Get files changed since a timestamp (for incremental backup)
    std::vector<FileEntry> changes_since(i64 timestamp_ms) {
        Buffer req;
        encode_i64(req, timestamp_ms);
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_changes_since, req);
        return decode_array_FileEntry(resp);
    }

    /// Receive a file chunk (upload to this agent)
    ChunkResult receive_chunk(const FileChunk& chunk) {
        Buffer req;
        encode_FileChunk(req, chunk);
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_receive_chunk, req);
        return decode_ChunkResult(resp);
    }

    /// Delete a file
    bool delete_file(const std::string& path) {
        Buffer req;
        encode_string(req, path);
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_delete_file, req);
        return decode_bool(resp);
    }

    /// Get current operation progress
    Progress get_progress() {
        Buffer req;
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_get_progress, req);
        return decode_Progress(resp);
    }

    /// Get total storage used in bytes
    i64 get_storage_used() {
        Buffer req;
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_get_storage_used, req);
        return decode_i64(resp);
    }

    /// Compute checksum for a file
    std::string compute_checksum(const std::string& path) {
        Buffer req;
        encode_string(req, path);
        Buffer resp = m_conn.call(kService_BackupAgent, kMethod_BackupAgent_compute_checksum, req);
        return decode_string(resp);
    }

};

/// Backup agent service (interface)
class IBackupAgent {
public:
    virtual ~IBackupAgent() = default;

    /// List all files under the backup root
    virtual std::vector<FileEntry> list_files() = 0;
    /// Get info about a specific file
    virtual FileEntry get_file_info(const std::string& path) = 0;
    /// Check if a file exists
    virtual bool file_exists(const std::string& path) = 0;
    /// Get files changed since a timestamp (for incremental backup)
    virtual std::vector<FileEntry> changes_since(i64 timestamp_ms) = 0;
    /// Receive a file chunk (upload to this agent)
    virtual ChunkResult receive_chunk(const FileChunk& chunk) = 0;
    /// Delete a file
    virtual bool delete_file(const std::string& path) = 0;
    /// Get current operation progress
    virtual Progress get_progress() = 0;
    /// Get total storage used in bytes
    virtual i64 get_storage_used() = 0;
    /// Compute checksum for a file
    virtual std::string compute_checksum(const std::string& path) = 0;
};

inline void dispatch_BackupAgent(IBackupAgent& impl, u16 method_id, Buffer& request, Buffer& response) {
    switch (method_id) {
        case kMethod_BackupAgent_list_files: {
            auto result = impl.list_files();
            encode_array_FileEntry(response, result);
            break;
        }
        case kMethod_BackupAgent_get_file_info: {
            std::string path = decode_string(request);
            auto result = impl.get_file_info(path);
            encode_FileEntry(response, result);
            break;
        }
        case kMethod_BackupAgent_file_exists: {
            std::string path = decode_string(request);
            auto result = impl.file_exists(path);
            encode_bool(response, result);
            break;
        }
        case kMethod_BackupAgent_changes_since: {
            i64 timestamp_ms = decode_i64(request);
            auto result = impl.changes_since(timestamp_ms);
            encode_array_FileEntry(response, result);
            break;
        }
        case kMethod_BackupAgent_receive_chunk: {
            FileChunk chunk = decode_FileChunk(request);
            auto result = impl.receive_chunk(chunk);
            encode_ChunkResult(response, result);
            break;
        }
        case kMethod_BackupAgent_delete_file: {
            std::string path = decode_string(request);
            auto result = impl.delete_file(path);
            encode_bool(response, result);
            break;
        }
        case kMethod_BackupAgent_get_progress: {
            auto result = impl.get_progress();
            encode_Progress(response, result);
            break;
        }
        case kMethod_BackupAgent_get_storage_used: {
            auto result = impl.get_storage_used();
            encode_i64(response, result);
            break;
        }
        case kMethod_BackupAgent_compute_checksum: {
            std::string path = decode_string(request);
            auto result = impl.compute_checksum(path);
            encode_string(response, result);
            break;
        }
        default:
            throw std::runtime_error("Unknown method ID: " + std::to_string(method_id));
    }
}

} // namespace song::backup
