// MIT License
// Copyright (c) 2026 dbjwhs

// Generated by songc - DO NOT EDIT
// Source: calculator.song

#pragma once

#include <song/song.hpp>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>

namespace song::calculator {

using namespace song;

// Service and method IDs
constexpr u16 kService_Calculator = 1;
constexpr u16 kMethod_Calculator_add = 1;
constexpr u16 kMethod_Calculator_subtract = 2;
constexpr u16 kMethod_Calculator_multiply = 3;
constexpr u16 kMethod_Calculator_divide = 4;

struct DivResult;

/// Result of a division operation
struct DivResult {
    /// The quotient
    i32 quotient;
    /// The remainder
    i32 remainder;
};

// Serialization
inline void encode_DivResult(Buffer& buf, const DivResult& val) {
    encode_i32(buf, val.quotient);
    encode_i32(buf, val.remainder);
}

inline DivResult decode_DivResult(Buffer& buf) {
    DivResult val;
    val.quotient = decode_i32(buf);
    val.remainder = decode_i32(buf);
    return val;
}

/// Simple calculator service
class CalculatorProxy {
    ServiceConnection& m_conn;
public:
    explicit CalculatorProxy(ServiceConnection& conn) : m_conn(conn) {}

    /// Add two numbers
    i32 add(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_add, req);
        return decode_i32(resp);
    }

    /// Subtract b from a
    i32 subtract(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_subtract, req);
        return decode_i32(resp);
    }

    /// Multiply two numbers
    i32 multiply(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_multiply, req);
        return decode_i32(resp);
    }

    /// Divide a by b, returning quotient and remainder
    DivResult divide(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_divide, req);
        return decode_DivResult(resp);
    }

};

/// Simple calculator service (interface)
class ICalculator {
public:
    virtual ~ICalculator() = default;

    /// Add two numbers
    virtual i32 add(i32 a, i32 b) = 0;
    /// Subtract b from a
    virtual i32 subtract(i32 a, i32 b) = 0;
    /// Multiply two numbers
    virtual i32 multiply(i32 a, i32 b) = 0;
    /// Divide a by b, returning quotient and remainder
    virtual DivResult divide(i32 a, i32 b) = 0;
};

inline void dispatch_Calculator(ICalculator& impl, u16 method_id, Buffer& request, Buffer& response) {
    switch (method_id) {
        case kMethod_Calculator_add: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.add(a, b);
            encode_i32(response, result);
            break;
        }
        case kMethod_Calculator_subtract: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.subtract(a, b);
            encode_i32(response, result);
            break;
        }
        case kMethod_Calculator_multiply: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.multiply(a, b);
            encode_i32(response, result);
            break;
        }
        case kMethod_Calculator_divide: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.divide(a, b);
            encode_DivResult(response, result);
            break;
        }
        default:
            throw std::runtime_error("Unknown method ID: " + std::to_string(method_id));
    }
}

} // namespace song::calculator
