// MIT License
// Copyright (c) 2026 dbjwhs

#include <song/song.hpp>
#include <iostream>
#include <string>

using namespace song;

// Service IDs
constexpr u16 kService_Echo = 1;

// Method IDs
constexpr u16 kMethod_echo = 1;
constexpr u16 kMethod_add = 2;
constexpr u16 kMethod_double_all = 3;

// Echo proxy - manually written (would be generated by songc)
class EchoProxy {
    ServiceConnection& conn_;

public:
    explicit EchoProxy(ServiceConnection& conn) : conn_(conn) {}

    std::string echo(const std::string& msg) {
        Buffer req;
        encode_string(req, msg);
        Buffer resp = conn_.call(kService_Echo, kMethod_echo, req);
        return decode_string(resp);
    }

    i32 add(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = conn_.call(kService_Echo, kMethod_add, req);
        return decode_i32(resp);
    }

    std::vector<i32> double_all(std::span<const i32> vals) {
        Buffer req;
        encode_array<i32>(req, vals);
        Buffer resp = conn_.call(kService_Echo, kMethod_double_all, req);
        return decode_array<i32>(resp);
    }
};

int main() {
    try {
        // Create service manager
        ServiceManager mgr;

        // Register echo service (use absolute path to built executable)
        mgr.register_service("echo", "/Users/dbjones/ng/dbjwhs/song/build/examples/echo_service", 1);

        // Connect to service (will start it)
        auto conn = mgr.connect("echo");
        EchoProxy proxy(conn);

        // Show negotiated version
        u16 ver = conn.process()->negotiated_version();
        std::cout << "Negotiated protocol version: "
                  << (ver >> 8) << "." << (ver & 0xFF) << "\n";

        // Show method capabilities
        std::cout << "Service supports " << conn.process()->methods().size() << " methods:\n";
        for (const auto& m : conn.process()->methods()) {
            std::cout << "  service=" << m.service_id << " method=" << m.method_id << "\n";
        }

        // Test supports() API
        std::cout << "\nCapability checks:\n";
        std::cout << "  supports echo: " << (conn.supports(kService_Echo, kMethod_echo) ? "yes" : "no") << "\n";
        std::cout << "  supports add: " << (conn.supports(kService_Echo, kMethod_add) ? "yes" : "no") << "\n";
        std::cout << "  supports double_all: " << (conn.supports(kService_Echo, kMethod_double_all) ? "yes" : "no") << "\n";
        std::cout << "  supports unknown (99): " << (conn.supports(kService_Echo, 99) ? "yes" : "no") << "\n\n";

        // Test echo
        std::cout << "Testing echo method...\n";
        std::string result = proxy.echo("Hello, Song!");
        std::cout << "Echo result: " << result << "\n";

        // Test add
        std::cout << "\nTesting add method...\n";
        i32 sum = proxy.add(42, 58);
        std::cout << "Add result: " << sum << "\n";

        // Test multiple calls (process reuse)
        std::cout << "\nTesting multiple calls...\n";
        for (int ndx = 0; ndx < 5; ++ndx) {
            i32 r = proxy.add(ndx, ndx);
            std::cout << ndx << " + " << ndx << " = " << r << "\n";
        }

        // Test array serialization
        std::cout << "\nTesting array serialization...\n";
        std::vector<i32> input = {1, 2, 3, 4, 5};
        std::vector<i32> doubled = proxy.double_all(input);
        std::cout << "Input:  ";
        for (auto v : input) std::cout << v << " ";
        std::cout << "\nDoubled: ";
        for (auto v : doubled) std::cout << v << " ";
        std::cout << "\n";

        // Verify results
        bool array_ok = (doubled.size() == input.size());
        for (size_t i = 0; array_ok && i < input.size(); ++i) {
            array_ok = (doubled[i] == input[i] * 2);
        }
        if (!array_ok) {
            std::cerr << "Array test failed!\n";
            return 1;
        }

        std::cout << "\nAll tests passed!\n";

    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
