// MIT License
// Copyright (c) 2026 dbjwhs

#include <song/song.hpp>
#include <iostream>
#include <string>

using namespace song;

// Service IDs
constexpr u16 kService_Echo = 1;

// Method IDs
constexpr u16 kMethod_echo = 1;
constexpr u16 kMethod_add = 2;

// Echo proxy - manually written (would be generated by songc)
class EchoProxy {
    ServiceConnection& conn_;

public:
    explicit EchoProxy(ServiceConnection& conn) : conn_(conn) {}

    std::string echo(const std::string& msg) {
        Buffer req;
        encode_string(req, msg);
        Buffer resp = conn_.call(kService_Echo, kMethod_echo, req);
        return decode_string(resp);
    }

    i32 add(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = conn_.call(kService_Echo, kMethod_add, req);
        return decode_i32(resp);
    }
};

int main() {
    try {
        // Create service manager
        ServiceManager mgr;

        // Register echo service (use absolute path to built executable)
        mgr.register_service("echo", "/Users/dbjones/ng/dbjwhs/song/build/examples/echo_service", 1);

        // Connect to service (will start it)
        auto conn = mgr.connect("echo");
        EchoProxy proxy(conn);

        // Test echo
        std::cout << "Testing echo method...\n";
        std::string result = proxy.echo("Hello, Song!");
        std::cout << "Echo result: " << result << "\n";

        // Test add
        std::cout << "\nTesting add method...\n";
        i32 sum = proxy.add(42, 58);
        std::cout << "Add result: " << sum << "\n";

        // Test multiple calls (process reuse)
        std::cout << "\nTesting multiple calls...\n";
        for (int i = 0; i < 5; ++i) {
            i32 r = proxy.add(i, i);
            std::cout << i << " + " << i << " = " << r << "\n";
        }

        std::cout << "\nAll tests passed!\n";

    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
