// MIT License
// Copyright (c) 2026 dbjwhs

// Generated by songc - DO NOT EDIT
// Source: chat.song

#pragma once

#include <song/song.hpp>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>

namespace song::chat {

using namespace song;

// Service and method IDs
constexpr u16 kService_Chat = 1;
constexpr u16 kMethod_Chat_send = 1;
constexpr u16 kMethod_Chat_get_history = 2;
constexpr u16 kMethod_Chat_get_messages_after = 3;
constexpr u16 kMethod_Chat_clear_history = 4;
constexpr u16 kMethod_Chat_get_message_count = 5;
constexpr u16 kMethod_Chat_message_exists = 6;

struct Message;
struct SendResult;
struct HistoryResult;

/// A chat message with metadata
struct Message {
    /// Unique message ID
    i64 id;
    /// Message sender name
    std::string sender;
    /// Message content
    std::string content;
    /// Timestamp when sent (unix milliseconds)
    i64 timestamp;
};

/// Server response after sending a message
struct SendResult {
    /// Whether the message was accepted
    bool success;
    /// Assigned message ID
    i64 message_id;
    /// Server timestamp
    i64 timestamp;
};

/// Chat history query result
struct HistoryResult {
    /// Messages in chronological order
    std::vector<Message> messages;
    /// Total number of messages in history
    i32 total_count;
    /// Whether there are more messages
    bool has_more;
};

// Forward declare array helpers
inline void encode_array_Message(Buffer& buf, const std::vector<Message>& arr);
inline std::vector<Message> decode_array_Message(Buffer& buf);
inline void encode_array_SendResult(Buffer& buf, const std::vector<SendResult>& arr);
inline std::vector<SendResult> decode_array_SendResult(Buffer& buf);
inline void encode_array_HistoryResult(Buffer& buf, const std::vector<HistoryResult>& arr);
inline std::vector<HistoryResult> decode_array_HistoryResult(Buffer& buf);

// Serialization
inline void encode_Message(Buffer& buf, const Message& val) {
    encode_i64(buf, val.id);
    encode_string(buf, val.sender);
    encode_string(buf, val.content);
    encode_i64(buf, val.timestamp);
}

inline Message decode_Message(Buffer& buf) {
    Message val;
    val.id = decode_i64(buf);
    val.sender = decode_string(buf);
    val.content = decode_string(buf);
    val.timestamp = decode_i64(buf);
    return val;
}

inline void encode_SendResult(Buffer& buf, const SendResult& val) {
    encode_bool(buf, val.success);
    encode_i64(buf, val.message_id);
    encode_i64(buf, val.timestamp);
}

inline SendResult decode_SendResult(Buffer& buf) {
    SendResult val;
    val.success = decode_bool(buf);
    val.message_id = decode_i64(buf);
    val.timestamp = decode_i64(buf);
    return val;
}

inline void encode_HistoryResult(Buffer& buf, const HistoryResult& val) {
    encode_array_Message(buf, val.messages);
    encode_i32(buf, val.total_count);
    encode_bool(buf, val.has_more);
}

inline HistoryResult decode_HistoryResult(Buffer& buf) {
    HistoryResult val;
    val.messages = decode_array_Message(buf);
    val.total_count = decode_i32(buf);
    val.has_more = decode_bool(buf);
    return val;
}

inline void encode_array_Message(Buffer& buf, const std::vector<Message>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_Message(buf, val);
    }
}

inline std::vector<Message> decode_array_Message(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<Message> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_Message(buf));
    }
    return arr;
}

inline void encode_array_SendResult(Buffer& buf, const std::vector<SendResult>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_SendResult(buf, val);
    }
}

inline std::vector<SendResult> decode_array_SendResult(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<SendResult> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_SendResult(buf));
    }
    return arr;
}

inline void encode_array_HistoryResult(Buffer& buf, const std::vector<HistoryResult>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_HistoryResult(buf, val);
    }
}

inline std::vector<HistoryResult> decode_array_HistoryResult(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<HistoryResult> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_HistoryResult(buf));
    }
    return arr;
}

/// Chat service for sending and retrieving messages
class ChatProxy {
    ServiceConnection& m_conn;
public:
    explicit ChatProxy(ServiceConnection& conn) : m_conn(conn) {}

    /// Send a message to the chat
    SendResult send(const std::string& sender, const std::string& content) {
        Buffer req;
        encode_string(req, sender);
        encode_string(req, content);
        Buffer resp = m_conn.call(kService_Chat, kMethod_Chat_send, req);
        return decode_SendResult(resp);
    }

    /// Get recent message history (last N messages)
    HistoryResult get_history(i32 count) {
        Buffer req;
        encode_i32(req, count);
        Buffer resp = m_conn.call(kService_Chat, kMethod_Chat_get_history, req);
        return decode_HistoryResult(resp);
    }

    /// Get messages after a specific message ID
    HistoryResult get_messages_after(i64 after_id, i32 count) {
        Buffer req;
        encode_i64(req, after_id);
        encode_i32(req, count);
        Buffer resp = m_conn.call(kService_Chat, kMethod_Chat_get_messages_after, req);
        return decode_HistoryResult(resp);
    }

    /// Clear all message history
    i32 clear_history() {
        Buffer req;
        Buffer resp = m_conn.call(kService_Chat, kMethod_Chat_clear_history, req);
        return decode_i32(resp);
    }

    /// Get total message count
    i32 get_message_count() {
        Buffer req;
        Buffer resp = m_conn.call(kService_Chat, kMethod_Chat_get_message_count, req);
        return decode_i32(resp);
    }

    /// Check if a message exists
    bool message_exists(i64 message_id) {
        Buffer req;
        encode_i64(req, message_id);
        Buffer resp = m_conn.call(kService_Chat, kMethod_Chat_message_exists, req);
        return decode_bool(resp);
    }

};

/// Chat service for sending and retrieving messages (interface)
class IChat {
public:
    virtual ~IChat() = default;

    /// Send a message to the chat
    virtual SendResult send(const std::string& sender, const std::string& content) = 0;
    /// Get recent message history (last N messages)
    virtual HistoryResult get_history(i32 count) = 0;
    /// Get messages after a specific message ID
    virtual HistoryResult get_messages_after(i64 after_id, i32 count) = 0;
    /// Clear all message history
    virtual i32 clear_history() = 0;
    /// Get total message count
    virtual i32 get_message_count() = 0;
    /// Check if a message exists
    virtual bool message_exists(i64 message_id) = 0;
};

inline void dispatch_Chat(IChat& impl, u16 method_id, Buffer& request, Buffer& response) {
    switch (method_id) {
        case kMethod_Chat_send: {
            std::string sender = decode_string(request);
            std::string content = decode_string(request);
            auto result = impl.send(sender, content);
            encode_SendResult(response, result);
            break;
        }
        case kMethod_Chat_get_history: {
            i32 count = decode_i32(request);
            auto result = impl.get_history(count);
            encode_HistoryResult(response, result);
            break;
        }
        case kMethod_Chat_get_messages_after: {
            i64 after_id = decode_i64(request);
            i32 count = decode_i32(request);
            auto result = impl.get_messages_after(after_id, count);
            encode_HistoryResult(response, result);
            break;
        }
        case kMethod_Chat_clear_history: {
            auto result = impl.clear_history();
            encode_i32(response, result);
            break;
        }
        case kMethod_Chat_get_message_count: {
            auto result = impl.get_message_count();
            encode_i32(response, result);
            break;
        }
        case kMethod_Chat_message_exists: {
            i64 message_id = decode_i64(request);
            auto result = impl.message_exists(message_id);
            encode_bool(response, result);
            break;
        }
        default:
            throw std::runtime_error("Unknown method ID: " + std::to_string(method_id));
    }
}

} // namespace song::chat
