// MIT License
// Copyright (c) 2026 dbjwhs

// Generated by songc - DO NOT EDIT
// Source: calculator.song

#pragma once

#include <song/song.hpp>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>

namespace song::calculator {

using namespace song;

// Service and method IDs
constexpr u16 kService_Calculator = 1;
constexpr u16 kMethod_Calculator_add = 1;
constexpr u16 kMethod_Calculator_subtract = 2;
constexpr u16 kMethod_Calculator_multiply = 3;
constexpr u16 kMethod_Calculator_divide = 4;
constexpr u16 kMethod_Calculator_factorial = 5;
constexpr u16 kMethod_Calculator_sum = 6;
constexpr u16 kMethod_Calculator_sum_matrix = 7;
constexpr u16 kMethod_Calculator_transpose = 8;
constexpr u16 kMethod_Calculator_flatten_3d = 9;

struct DivResult;

/// Result of a division operation
struct DivResult {
    /// The quotient
    i32 quotient;
    /// The remainder
    i32 remainder;
};

// Forward declare array helpers
inline void encode_array_DivResult(Buffer& buf, const std::vector<DivResult>& arr);
inline std::vector<DivResult> decode_array_DivResult(Buffer& buf);

// Serialization
inline void encode_DivResult(Buffer& buf, const DivResult& val) {
    encode_i32(buf, val.quotient);
    encode_i32(buf, val.remainder);
}

inline DivResult decode_DivResult(Buffer& buf) {
    DivResult val;
    val.quotient = decode_i32(buf);
    val.remainder = decode_i32(buf);
    return val;
}

inline void encode_array_DivResult(Buffer& buf, const std::vector<DivResult>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_DivResult(buf, val);
    }
}

inline std::vector<DivResult> decode_array_DivResult(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<DivResult> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_DivResult(buf));
    }
    return arr;
}

/// Calculator service with basic arithmetic operations
class CalculatorProxy {
    ServiceConnection& m_conn;
public:
    explicit CalculatorProxy(ServiceConnection& conn) : m_conn(conn) {}

    /// Add two numbers
    i32 add(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_add, req);
        return decode_i32(resp);
    }

    /// Subtract b from a
    i32 subtract(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_subtract, req);
        return decode_i32(resp);
    }

    /// Multiply two numbers
    i32 multiply(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_multiply, req);
        return decode_i32(resp);
    }

    /// Integer division returning quotient and remainder
    DivResult divide(i32 a, i32 b) {
        Buffer req;
        encode_i32(req, a);
        encode_i32(req, b);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_divide, req);
        return decode_DivResult(resp);
    }

    /// Compute factorial (demonstrates larger computation)
    i64 factorial(i32 n) {
        Buffer req;
        encode_i32(req, n);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_factorial, req);
        return decode_i64(resp);
    }

    /// Sum an array of numbers
    i64 sum(const std::vector<i32>& values) {
        Buffer req;
        encode_array<i32>(req, values);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_sum, req);
        return decode_i64(resp);
    }

    /// Sum all elements in a 2D matrix
    f64 sum_matrix(const std::vector<std::vector<f64>>& matrix) {
        Buffer req;
        encode_array<std::vector<f64>>(req, matrix);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_sum_matrix, req);
        return decode_f64(resp);
    }

    /// Transpose a 2D matrix (swap rows and columns)
    std::vector<std::vector<i32>> transpose(const std::vector<std::vector<i32>>& matrix) {
        Buffer req;
        encode_array<std::vector<i32>>(req, matrix);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_transpose, req);
        return decode_array<std::vector<i32>>(resp);
    }

    /// Flatten a 3D array to 1D
    std::vector<i32> flatten_3d(const std::vector<std::vector<std::vector<i32>>>& cube) {
        Buffer req;
        encode_array<std::vector<std::vector<i32>>>(req, cube);
        Buffer resp = m_conn.call(kService_Calculator, kMethod_Calculator_flatten_3d, req);
        return decode_array<i32>(resp);
    }

};

/// Calculator service with basic arithmetic operations (interface)
class ICalculator {
public:
    virtual ~ICalculator() = default;

    /// Add two numbers
    virtual i32 add(i32 a, i32 b) = 0;
    /// Subtract b from a
    virtual i32 subtract(i32 a, i32 b) = 0;
    /// Multiply two numbers
    virtual i32 multiply(i32 a, i32 b) = 0;
    /// Integer division returning quotient and remainder
    virtual DivResult divide(i32 a, i32 b) = 0;
    /// Compute factorial (demonstrates larger computation)
    virtual i64 factorial(i32 n) = 0;
    /// Sum an array of numbers
    virtual i64 sum(const std::vector<i32>& values) = 0;
    /// Sum all elements in a 2D matrix
    virtual f64 sum_matrix(const std::vector<std::vector<f64>>& matrix) = 0;
    /// Transpose a 2D matrix (swap rows and columns)
    virtual std::vector<std::vector<i32>> transpose(const std::vector<std::vector<i32>>& matrix) = 0;
    /// Flatten a 3D array to 1D
    virtual std::vector<i32> flatten_3d(const std::vector<std::vector<std::vector<i32>>>& cube) = 0;
};

inline void dispatch_Calculator(ICalculator& impl, u16 method_id, Buffer& request, Buffer& response) {
    switch (method_id) {
        case kMethod_Calculator_add: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.add(a, b);
            encode_i32(response, result);
            break;
        }
        case kMethod_Calculator_subtract: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.subtract(a, b);
            encode_i32(response, result);
            break;
        }
        case kMethod_Calculator_multiply: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.multiply(a, b);
            encode_i32(response, result);
            break;
        }
        case kMethod_Calculator_divide: {
            i32 a = decode_i32(request);
            i32 b = decode_i32(request);
            auto result = impl.divide(a, b);
            encode_DivResult(response, result);
            break;
        }
        case kMethod_Calculator_factorial: {
            i32 n = decode_i32(request);
            auto result = impl.factorial(n);
            encode_i64(response, result);
            break;
        }
        case kMethod_Calculator_sum: {
            std::vector<i32> values = decode_array<i32>(request);
            auto result = impl.sum(values);
            encode_i64(response, result);
            break;
        }
        case kMethod_Calculator_sum_matrix: {
            std::vector<std::vector<f64>> matrix = decode_array<std::vector<f64>>(request);
            auto result = impl.sum_matrix(matrix);
            encode_f64(response, result);
            break;
        }
        case kMethod_Calculator_transpose: {
            std::vector<std::vector<i32>> matrix = decode_array<std::vector<i32>>(request);
            auto result = impl.transpose(matrix);
            encode_array<std::vector<i32>>(response, result);
            break;
        }
        case kMethod_Calculator_flatten_3d: {
            std::vector<std::vector<std::vector<i32>>> cube = decode_array<std::vector<std::vector<i32>>>(request);
            auto result = impl.flatten_3d(cube);
            encode_array<i32>(response, result);
            break;
        }
        default:
            throw std::runtime_error("Unknown method ID: " + std::to_string(method_id));
    }
}

} // namespace song::calculator
