# MIT License
# Copyright (c) 2026 dbjwhs

"""
Integration test: Python client connecting to C++ TCP Calculator service.

This test verifies that the Python client library can communicate with
a real C++ Song service over TCP.
"""

import unittest
import subprocess
import time
import os
import signal
from pathlib import Path

from song.buffer import Buffer
from song.connection import ServiceConnection, ServiceError


# Service/Method IDs (from calculator.hpp)
SERVICE_CALCULATOR = 1
METHOD_ADD = 1
METHOD_SUBTRACT = 2
METHOD_MULTIPLY = 3
METHOD_DIVIDE = 4
METHOD_FACTORIAL = 5
METHOD_SUM = 6

TEST_PORT = 18888


def find_service_executable() -> Path:
    """Find the TCP calculator service executable."""
    # Try common build locations
    candidates = [
        Path(__file__).parent.parent.parent / "build" / "sing" / "network" / "tcp_calculator" / "sing_network_tcp_calculator_service",
        Path.cwd() / "sing" / "network" / "tcp_calculator" / "sing_network_tcp_calculator_service",
    ]

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError("TCP calculator service not found. Run 'make' in build directory first.")


class CalculatorProxy:
    """
    Manual Python proxy for the Calculator service.

    In the future, this would be auto-generated by songc --lang=python.
    """

    def __init__(self, conn: ServiceConnection):
        self._conn = conn

    def add(self, a: int, b: int) -> int:
        """Add two integers."""
        req = Buffer()
        req.encode_i32(a)
        req.encode_i32(b)
        resp = self._conn.call(SERVICE_CALCULATOR, METHOD_ADD, req)
        return resp.decode_i32()

    def subtract(self, a: int, b: int) -> int:
        """Subtract b from a."""
        req = Buffer()
        req.encode_i32(a)
        req.encode_i32(b)
        resp = self._conn.call(SERVICE_CALCULATOR, METHOD_SUBTRACT, req)
        return resp.decode_i32()

    def multiply(self, a: int, b: int) -> int:
        """Multiply two integers."""
        req = Buffer()
        req.encode_i32(a)
        req.encode_i32(b)
        resp = self._conn.call(SERVICE_CALCULATOR, METHOD_MULTIPLY, req)
        return resp.decode_i32()

    def divide(self, a: int, b: int) -> tuple:
        """Divide a by b, returning (quotient, remainder)."""
        req = Buffer()
        req.encode_i32(a)
        req.encode_i32(b)
        resp = self._conn.call(SERVICE_CALCULATOR, METHOD_DIVIDE, req)
        quotient = resp.decode_i32()
        remainder = resp.decode_i32()
        return (quotient, remainder)

    def factorial(self, n: int) -> int:
        """Compute factorial of n."""
        req = Buffer()
        req.encode_i32(n)
        resp = self._conn.call(SERVICE_CALCULATOR, METHOD_FACTORIAL, req)
        return resp.decode_i64()

    def sum(self, values: list) -> int:
        """Sum a list of integers."""
        req = Buffer()
        req.encode_array_i32(values)
        resp = self._conn.call(SERVICE_CALCULATOR, METHOD_SUM, req)
        return resp.decode_i64()


class TestTcpCalculator(unittest.TestCase):
    """Integration tests for Python client against C++ TCP Calculator service."""

    server_process = None

    @classmethod
    def setUpClass(cls):
        """Start the TCP calculator service before tests."""
        try:
            service_path = find_service_executable()
        except FileNotFoundError as e:
            raise unittest.SkipTest(str(e))

        # Start the service
        cls.server_process = subprocess.Popen(
            [str(service_path), str(TEST_PORT)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        # Wait for service to start
        for _ in range(20):
            time.sleep(0.1)
            try:
                # Try connecting to verify service is up
                import socket
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(0.5)
                sock.connect(("127.0.0.1", TEST_PORT))
                sock.close()
                return
            except (socket.error, ConnectionRefusedError):
                pass

        # Service didn't start
        cls.server_process.terminate()
        cls.server_process = None
        raise unittest.SkipTest("Failed to start TCP calculator service")

    @classmethod
    def tearDownClass(cls):
        """Stop the TCP calculator service after tests."""
        if cls.server_process:
            cls.server_process.terminate()
            cls.server_process.wait()

    def test_add(self):
        """Test add operation."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            self.assertEqual(calc.add(2, 3), 5)
            self.assertEqual(calc.add(-10, 20), 10)
            self.assertEqual(calc.add(0, 0), 0)

    def test_subtract(self):
        """Test subtract operation."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            self.assertEqual(calc.subtract(10, 4), 6)
            self.assertEqual(calc.subtract(5, 10), -5)

    def test_multiply(self):
        """Test multiply operation."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            self.assertEqual(calc.multiply(6, 7), 42)
            self.assertEqual(calc.multiply(-3, 4), -12)

    def test_divide(self):
        """Test divide operation (returns quotient and remainder)."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            quotient, remainder = calc.divide(17, 5)
            self.assertEqual(quotient, 3)
            self.assertEqual(remainder, 2)

    def test_factorial(self):
        """Test factorial operation."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            self.assertEqual(calc.factorial(0), 1)
            self.assertEqual(calc.factorial(1), 1)
            self.assertEqual(calc.factorial(5), 120)
            self.assertEqual(calc.factorial(10), 3628800)

    def test_sum(self):
        """Test sum operation with array."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            self.assertEqual(calc.sum([1, 2, 3, 4, 5]), 15)
            self.assertEqual(calc.sum([]), 0)
            self.assertEqual(calc.sum([100]), 100)

    def test_multiple_operations(self):
        """Test multiple operations on same connection."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)

            # Perform multiple operations
            self.assertEqual(calc.add(10, 20), 30)
            self.assertEqual(calc.multiply(5, 5), 25)
            self.assertEqual(calc.subtract(100, 50), 50)
            self.assertEqual(calc.factorial(6), 720)

    def test_large_array(self):
        """Test sum with a larger array."""
        with ServiceConnection("127.0.0.1", TEST_PORT) as conn:
            calc = CalculatorProxy(conn)
            # Sum of 1 to 100 = 5050
            values = list(range(1, 101))
            self.assertEqual(calc.sum(values), 5050)


if __name__ == "__main__":
    unittest.main()
