// MIT License
// Copyright (c) 2026 dbjwhs

// Generated by songc - DO NOT EDIT
// Source: datacopy.song

#pragma once

#include <song/song.hpp>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>

namespace song::datacopy {

using namespace song;

// Service and method IDs
constexpr u16 kService_DataCopy = 1;
constexpr u16 kMethod_DataCopy_write_chunk = 1;
constexpr u16 kMethod_DataCopy_read_file = 2;
constexpr u16 kMethod_DataCopy_get_file_info = 3;
constexpr u16 kMethod_DataCopy_list_files = 4;
constexpr u16 kMethod_DataCopy_delete_file = 5;
constexpr u16 kMethod_DataCopy_clear_all = 6;
constexpr u16 kMethod_DataCopy_file_exists = 7;
constexpr u16 kMethod_DataCopy_get_storage_used = 8;

struct FileChunk;
struct WriteResult;
struct ReadResult;
struct FileInfo;

/// A chunk of file data
struct FileChunk {
    /// Filename being transferred
    std::string filename;
    /// Offset in bytes from start of file
    i64 offset;
    /// Chunk data
    std::vector<std::byte> data;
    /// Whether this is the last chunk
    bool is_final;
};

/// Result of a chunk write operation
struct WriteResult {
    /// Whether the write succeeded
    bool success;
    /// Number of bytes written
    i64 bytes_written;
    /// Total bytes received for this file so far
    i64 total_received;
};

/// Result of a file read operation
struct ReadResult {
    /// Whether the file exists
    bool found;
    /// File data (empty if not found)
    std::vector<std::byte> data;
    /// File size in bytes
    i64 size;
};

/// File metadata
struct FileInfo {
    /// Filename
    std::string filename;
    /// File size in bytes
    i64 size;
    /// Whether the file transfer is complete
    bool complete;
};

// Forward declare array helpers
inline void encode_array_FileChunk(Buffer& buf, const std::vector<FileChunk>& arr);
inline std::vector<FileChunk> decode_array_FileChunk(Buffer& buf);
inline void encode_array_WriteResult(Buffer& buf, const std::vector<WriteResult>& arr);
inline std::vector<WriteResult> decode_array_WriteResult(Buffer& buf);
inline void encode_array_ReadResult(Buffer& buf, const std::vector<ReadResult>& arr);
inline std::vector<ReadResult> decode_array_ReadResult(Buffer& buf);
inline void encode_array_FileInfo(Buffer& buf, const std::vector<FileInfo>& arr);
inline std::vector<FileInfo> decode_array_FileInfo(Buffer& buf);

// Serialization
inline void encode_FileChunk(Buffer& buf, const FileChunk& val) {
    encode_string(buf, val.filename);
    encode_i64(buf, val.offset);
    encode_bytes(buf, val.data);
    encode_bool(buf, val.is_final);
}

inline FileChunk decode_FileChunk(Buffer& buf) {
    FileChunk val;
    val.filename = decode_string(buf);
    val.offset = decode_i64(buf);
    val.data = decode_bytes(buf);
    val.is_final = decode_bool(buf);
    return val;
}

inline void encode_WriteResult(Buffer& buf, const WriteResult& val) {
    encode_bool(buf, val.success);
    encode_i64(buf, val.bytes_written);
    encode_i64(buf, val.total_received);
}

inline WriteResult decode_WriteResult(Buffer& buf) {
    WriteResult val;
    val.success = decode_bool(buf);
    val.bytes_written = decode_i64(buf);
    val.total_received = decode_i64(buf);
    return val;
}

inline void encode_ReadResult(Buffer& buf, const ReadResult& val) {
    encode_bool(buf, val.found);
    encode_bytes(buf, val.data);
    encode_i64(buf, val.size);
}

inline ReadResult decode_ReadResult(Buffer& buf) {
    ReadResult val;
    val.found = decode_bool(buf);
    val.data = decode_bytes(buf);
    val.size = decode_i64(buf);
    return val;
}

inline void encode_FileInfo(Buffer& buf, const FileInfo& val) {
    encode_string(buf, val.filename);
    encode_i64(buf, val.size);
    encode_bool(buf, val.complete);
}

inline FileInfo decode_FileInfo(Buffer& buf) {
    FileInfo val;
    val.filename = decode_string(buf);
    val.size = decode_i64(buf);
    val.complete = decode_bool(buf);
    return val;
}

inline void encode_array_FileChunk(Buffer& buf, const std::vector<FileChunk>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_FileChunk(buf, val);
    }
}

inline std::vector<FileChunk> decode_array_FileChunk(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<FileChunk> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_FileChunk(buf));
    }
    return arr;
}

inline void encode_array_WriteResult(Buffer& buf, const std::vector<WriteResult>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_WriteResult(buf, val);
    }
}

inline std::vector<WriteResult> decode_array_WriteResult(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<WriteResult> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_WriteResult(buf));
    }
    return arr;
}

inline void encode_array_ReadResult(Buffer& buf, const std::vector<ReadResult>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_ReadResult(buf, val);
    }
}

inline std::vector<ReadResult> decode_array_ReadResult(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<ReadResult> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_ReadResult(buf));
    }
    return arr;
}

inline void encode_array_FileInfo(Buffer& buf, const std::vector<FileInfo>& arr) {
    encode_u32(buf, static_cast<u32>(arr.size()));
    for (const auto& val : arr) {
        encode_FileInfo(buf, val);
    }
}

inline std::vector<FileInfo> decode_array_FileInfo(Buffer& buf) {
    u32 count = decode_u32(buf);
    std::vector<FileInfo> arr;
    arr.reserve(count);
    for (u32 i = 0; i < count; ++i) {
        arr.push_back(decode_FileInfo(buf));
    }
    return arr;
}

/// Data copy service for transferring files
class DataCopyProxy {
    ServiceConnection& m_conn;
public:
    explicit DataCopyProxy(ServiceConnection& conn) : m_conn(conn) {}

    /// Write a chunk of data to a file
    WriteResult write_chunk(const FileChunk& chunk) {
        Buffer req;
        encode_FileChunk(req, chunk);
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_write_chunk, req);
        return decode_WriteResult(resp);
    }

    /// Read an entire file
    ReadResult read_file(const std::string& filename) {
        Buffer req;
        encode_string(req, filename);
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_read_file, req);
        return decode_ReadResult(resp);
    }

    /// Get info about a file
    FileInfo get_file_info(const std::string& filename) {
        Buffer req;
        encode_string(req, filename);
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_get_file_info, req);
        return decode_FileInfo(resp);
    }

    /// List all files on the server
    std::vector<FileInfo> list_files() {
        Buffer req;
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_list_files, req);
        return decode_array_FileInfo(resp);
    }

    /// Delete a file
    bool delete_file(const std::string& filename) {
        Buffer req;
        encode_string(req, filename);
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_delete_file, req);
        return decode_bool(resp);
    }

    /// Clear all files
    i32 clear_all() {
        Buffer req;
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_clear_all, req);
        return decode_i32(resp);
    }

    /// Check if a file exists
    bool file_exists(const std::string& filename) {
        Buffer req;
        encode_string(req, filename);
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_file_exists, req);
        return decode_bool(resp);
    }

    /// Get total storage used
    i64 get_storage_used() {
        Buffer req;
        Buffer resp = m_conn.call(kService_DataCopy, kMethod_DataCopy_get_storage_used, req);
        return decode_i64(resp);
    }

};

/// Data copy service for transferring files (interface)
class IDataCopy {
public:
    virtual ~IDataCopy() = default;

    /// Write a chunk of data to a file
    virtual WriteResult write_chunk(const FileChunk& chunk) = 0;
    /// Read an entire file
    virtual ReadResult read_file(const std::string& filename) = 0;
    /// Get info about a file
    virtual FileInfo get_file_info(const std::string& filename) = 0;
    /// List all files on the server
    virtual std::vector<FileInfo> list_files() = 0;
    /// Delete a file
    virtual bool delete_file(const std::string& filename) = 0;
    /// Clear all files
    virtual i32 clear_all() = 0;
    /// Check if a file exists
    virtual bool file_exists(const std::string& filename) = 0;
    /// Get total storage used
    virtual i64 get_storage_used() = 0;
};

inline void dispatch_DataCopy(IDataCopy& impl, u16 method_id, Buffer& request, Buffer& response) {
    switch (method_id) {
        case kMethod_DataCopy_write_chunk: {
            FileChunk chunk = decode_FileChunk(request);
            auto result = impl.write_chunk(chunk);
            encode_WriteResult(response, result);
            break;
        }
        case kMethod_DataCopy_read_file: {
            std::string filename = decode_string(request);
            auto result = impl.read_file(filename);
            encode_ReadResult(response, result);
            break;
        }
        case kMethod_DataCopy_get_file_info: {
            std::string filename = decode_string(request);
            auto result = impl.get_file_info(filename);
            encode_FileInfo(response, result);
            break;
        }
        case kMethod_DataCopy_list_files: {
            auto result = impl.list_files();
            encode_array_FileInfo(response, result);
            break;
        }
        case kMethod_DataCopy_delete_file: {
            std::string filename = decode_string(request);
            auto result = impl.delete_file(filename);
            encode_bool(response, result);
            break;
        }
        case kMethod_DataCopy_clear_all: {
            auto result = impl.clear_all();
            encode_i32(response, result);
            break;
        }
        case kMethod_DataCopy_file_exists: {
            std::string filename = decode_string(request);
            auto result = impl.file_exists(filename);
            encode_bool(response, result);
            break;
        }
        case kMethod_DataCopy_get_storage_used: {
            auto result = impl.get_storage_used();
            encode_i64(response, result);
            break;
        }
        default:
            throw std::runtime_error("Unknown method ID: " + std::to_string(method_id));
    }
}

} // namespace song::datacopy
